# permissions for end users to edit keycloakclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-editor-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients/status
  verbs:
  - get
