# permissions for end users to view keycloakrealms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakrealm-viewer-role
rules:
- apiGroups:
  - keycloak.org.jaconi.io
  resources:
  - keycloakrealms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org.jaconi.io
  resources:
  - keycloakrealms/status
  verbs:
  - get
