# This rule is not used by the project keycloak-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to keycloak.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-viewer-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks/status
  verbs:
  - get
