# permissions for end users to view keycloakusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakuser-viewer-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloakusers/status
  verbs:
  - get
