# This rule is not used by the project keycloak-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over keycloak.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-admin-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients
  verbs:
  - '*'
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients/status
  verbs:
  - get
