# permissions for end users to view keycloakclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-viewer-role
rules:
- apiGroups:
  - keycloak.org.jaconi.io
  resources:
  - keycloakclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org.jaconi.io
  resources:
  - keycloakclients/status
  verbs:
  - get
