apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclient-sample
spec:
  # TODO(user): Add fields here
